services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.0.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
  grafana:
    container_name: grafana
    image: grafana/grafana:11.3.1
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  prometheus_data: {}
  grafana_data: {}