services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.0.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  grafana:
    container_name: grafana
    image: grafana/grafana:11.3.1
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana:/var/lib/grafana



